apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: my-app-namespace  # Ensure the namespace is correctly set
spec:
  type: NodePort
  selector:
    app: backend-app
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30005

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: my-app-namespace  # Ensure the namespace is correctly set
spec:
  type: NodePort
  selector:
    app: frontend-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30006

