apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend-app
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30001

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30002

