name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker to use Minikube's environment
    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        eval $(minikube docker-env)

    # Step 3: Build the Docker images
    - name: Build Docker image
      run: |
        docker build -t hassan3011/my-app-backend:latest -f backend/Dockerfile .
        docker build -t hassan3011/my-app-frontend:latest -f frontend/Dockerfile .

    # Step 4: Login to Docker Hub using secrets
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 5: Push Docker images to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push hassan3011/my-app-backend:latest
        docker push hassan3011/my-app-frontend:latest

    # Step 6: Deploy to Minikube (Apply Kubernetes manifests)
    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yaml --namespace=my-app-namespace
        kubectl apply -f k8s/service.yaml --namespace=my-app-namespace

