name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main  # This will trigger the workflow on every push to the main branch.

jobs:
  build-deploy:
    runs-on: self-hosted  # This will use the self-hosted runner on your local machine.

    steps:
    # Checkout the repository's code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker to use Minikube's environment
    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        eval $(minikube docker-env)  # Configures Docker to use Minikube's Docker daemon

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t hassan3011/my-app-backend:latest ./backend  # Adjust paths as needed
        docker build -t hassan3011/my-app-frontend:latest ./frontend  # Adjust paths as needed

    # Log in to Docker Hub
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push hassan3011/my-app-backend:latest
        docker push hassan3011/my-app-frontend:latest

    # Deploy the app to Minikube using kubectl
    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml  # Apply the deployment.yaml file
        kubectl apply -f service.yaml  # Apply the service.yaml file
